In [138]:
import pandas as pd

df = pd.read_csv('autos.csv')


print(df)

     symboling         make fuel_type aspiration  num_of_doors   body_style  \
0            3  alfa-romero       gas        std             2  convertible
1            3  alfa-romero       gas        std             2  convertible
2            1  alfa-romero       gas        std             2    hatchback
3            2         audi       gas        std             4        sedan
4            2         audi       gas        std             4        sedan
..         ...          ...       ...        ...           ...          ...
188         -1        volvo       gas        std             4        sedan
189         -1        volvo       gas      turbo             4        sedan
190         -1        volvo       gas        std             4        sedan
191         -1        volvo    diesel      turbo             4        sedan
192         -1        volvo       gas      turbo             4        sedan

    drive_wheels engine_location  wheel_base  length  ...  engine_size  \
0            rwd           front        88.6   168.8  ...          130
1            rwd           front        88.6   168.8  ...          130
2            rwd           front        94.5   171.2  ...          152
3            fwd           front        99.8   176.6  ...          109
4            4wd           front        99.4   176.6  ...          136
..           ...             ...         ...     ...  ...          ...
188          rwd           front       109.1   188.8  ...          141
189          rwd           front       109.1   188.8  ...          141
190          rwd           front       109.1   188.8  ...          173
191          rwd           front       109.1   188.8  ...          145
192          rwd           front       109.1   188.8  ...          141

     fuel_system  bore stroke  compression_ratio  horsepower peak_rpm  \
0           mpfi  3.47   2.68                  9         111     5000
1           mpfi  3.47   2.68                  9         111     5000
2           mpfi  2.68   3.47                  9         154     5000
3           mpfi  3.19   3.40                 10         102     5500
4           mpfi  3.19   3.40                  8         115     5500
..           ...   ...    ...                ...         ...      ...
188         mpfi  3.78   3.15                  9         114     5400
189         mpfi  3.78   3.15                  8         160     5300
190         mpfi  3.58   2.87                  8         134     5500
191          idi  3.01   3.40                 23         106     4800
192         mpfi  3.78   3.15                  9         114     5400

     city_mpg  highway_mpg  price
0          21           27  13495
1          21           27  16500
2          19           26  16500
3          24           30  13950
4          18           22  17450
..        ...          ...    ...
188        23           28  16845
189        19           25  19045
190        18           23  21485
191        26           27  22470
192        19           25  22625

[193 rows x 25 columns]

In [5]:
df.head(8)

,symboling,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9,111,5000,21,27,13495
1,3,alfa-romero,gas,std,2,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9,111,5000,21,27,16500
2,1,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9,154,5000,19,26,16500
3,2,audi,gas,std,4,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10,102,5500,24,30,13950
4,2,audi,gas,std,4,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8,115,5500,18,22,17450
5,2,audi,gas,std,2,sedan,fwd,front,99.8,177.3,...,136,mpfi,3.19,3.40,8,110,5500,19,25,15250
6,1,audi,gas,std,4,sedan,fwd,front,105.8,192.7,...,136,mpfi,3.19,3.40,8,110,5500,19,25,17710
7,1,audi,gas,std,4,wagon,fwd,front,105.8,192.7,...,136,mpfi,3.19,3.40,8,110,5500,19,25,18920

In [6]:
df.tail(8)

,symboling,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
185,-1,volvo,gas,std,4,wagon,rwd,front,104.3,188.8,...,141,mpfi,3.78,3.15,9,114,5400,24,28,16515
186,-2,volvo,gas,turbo,4,sedan,rwd,front,104.3,188.8,...,130,mpfi,3.62,3.15,7,162,5100,17,22,18420
187,-1,volvo,gas,turbo,4,wagon,rwd,front,104.3,188.8,...,130,mpfi,3.62,3.15,7,162,5100,17,22,18950
188,-1,volvo,gas,std,4,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9,114,5400,23,28,16845
189,-1,volvo,gas,turbo,4,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8,160,5300,19,25,19045
190,-1,volvo,gas,std,4,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8,134,5500,18,23,21485
191,-1,volvo,diesel,turbo,4,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23,106,4800,26,27,22470
192,-1,volvo,gas,turbo,4,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9,114,5400,19,25,22625

In [115]:
 df.groupby('make')['price'].min()
print(min_price_df)

             make  min_price
0     alfa-romero      13495
1            audi      13950
2             bmw      16430
3       chevrolet       5151
4           dodge       5572
5           honda       5399
6           isuzu       6785
7          jaguar      32250
8           mazda       5195
9   mercedes-benz      25552
10        mercury      16503
11     mitsubishi       5389
12         nissan       5499
13         peugot      11900
14       plymouth       5572
15        porsche      22018
16           saab      11850
17         subaru       5118
18         toyota       5348
19     volkswagen       7775
20          volvo      12940

In [132]:
df.min_std = stds.min()
print('The smallest standard deviation of the prices is:', min_std)

The smallest standard deviation of the prices is: 1676.8283892533195

In [127]:
df[['make', 'fuel_type']].tail(2)

      make fuel_type
191  volvo    diesel
192  volvo       gas

In [143]:


dit={'make': ['audi', 'Honda', 'porsche', 'nissan'],
                    'year': [2022, 2021, 2020, 2019],
                    'price': [75000, 88000, 92000, 10000]}
dit2 ={'make': ['audi', 'Honda', 'porsche', 'nissan'],
                    'mpg': [23, 24, 29, 25],
                    'transmission': ['automatic', 'manual', 'manual', 'automatic']}
df1=pd.DataFrame(dit)
df2=pd.DataFrame(dit2)
merged_df = pd.merge(df1, df2, on='make')

print(merged_df)

      make  year  price  mpg transmission
0     audi  2022  75000   23    automatic
1    Honda  2021  88000   24       manual
2  porsche  2020  92000   29       manual
3   nissan  2019  10000   25    automatic